# Generated by Django 3.0.5 on 2020-04-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('_from', models.CharField(max_length=150)),
                ('train_number', models.CharField(blank=True, max_length=150, unique=True)),
                ('to', models.TextField(blank=True)),
                ('date_out', models.DateTimeField()),
            ],
        ),
    ]
