# Generated by Django 3.0.5 on 2020-04-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='way',
            old_name='_from',
            new_name='first_station',
        ),
    ]
