# Generated by Django 3.0.5 on 2020-04-16 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='number_of_place',
            field=models.IntegerField(default=0, verbose_name='Номер місця'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='place_type',
            field=models.CharField(default=None, max_length=20, verbose_name='Тип вагону'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='arival',
            field=models.DateTimeField(verbose_name='Час прибуття'),
        ),
        migrations.AlterField(
            model_name='station',
            name='departure',
            field=models.DateTimeField(verbose_name='Час відʼїзду'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Станція'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_purchase',
            field=models.DateTimeField(auto_now=True, verbose_name='дата відправки'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='destination',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='railway.Way', to_field='name', verbose_name='Кінцева Станція'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Номер квитка'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Назва поїзду'),
        ),
        migrations.AlterField(
            model_name='way',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name="ім'я шляху"),
        ),
        migrations.AlterField(
            model_name='way',
            name='stations',
            field=models.ManyToManyField(to='railway.Station', verbose_name='Станції'),
        ),
        migrations.AlterField(
            model_name='way',
            name='train',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='railway.Train', to_field='name', verbose_name='Номер поїзду'),
        ),
    ]
