# Generated by Django 3.0.5 on 2020-04-13 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_auto_20200413_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=32, unique=True)),
                ('departure', models.DateTimeField()),
                ('arival', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='way',
            name='date_out',
        ),
        migrations.RemoveField(
            model_name='way',
            name='first_station',
        ),
        migrations.RemoveField(
            model_name='way',
            name='to',
        ),
        migrations.RemoveField(
            model_name='way',
            name='train_number',
        ),
        migrations.AlterField(
            model_name='way',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('date_purchase', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='railway.Way', to_field='name')),
            ],
        ),
        migrations.AddField(
            model_name='way',
            name='stations',
            field=models.ManyToManyField(to='railway.Station'),
        ),
        migrations.AddField(
            model_name='way',
            name='train',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='railway.Train', to_field='name'),
        ),
    ]
