# Generated by Django 3.0.5 on 2020-04-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0003_auto_20200416_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='carriage',
            field=models.DateTimeField(default=None, verbose_name='Номер вагону'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='first',
            field=models.DateTimeField(default=None, verbose_name='дата прибуття'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='service',
            field=models.CharField(default=None, max_length=20, verbose_name='Послуги'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_purchase',
            field=models.DateTimeField(verbose_name='дата відправки'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type_of_ticket',
            field=models.CharField(max_length=20, verbose_name='Тип квитка'),
        ),
    ]
