# Generated by Django 3.0.5 on 2020-04-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0005_auto_20200416_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='carriage',
            field=models.IntegerField(default=None, verbose_name='Номер вагону'),
        ),
    ]
