# Generated by Django 3.0.5 on 2020-04-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0006_auto_20200416_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='service',
            field=models.CharField(choices=[('Пб', 'Постільна білизна'), ('Вд', 'Вода'), ('Гн', 'Гарячі напої')], default=None, max_length=20, verbose_name='Послуги'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type_of_ticket',
            field=models.CharField(choices=[('Ст', 'Студентський квиток'), ('Пл', 'Пільговий'), ('Пв', 'Повний')], max_length=20, verbose_name='Тип квитка'),
        ),
    ]
