# Generated by Django 3.0.5 on 2020-04-16 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0007_auto_20200417_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='carriage',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], default=None, verbose_name='Номер вагону'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_purchase',
            field=models.DateTimeField(verbose_name='Дата відправлення'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='destination',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='railway.Way', to_field='name', verbose_name='Кінцева станція'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='first',
            field=models.DateTimeField(default=None, verbose_name='Дата прибуття'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number_of_place',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40')], default=None, verbose_name='Номер місця'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='place_type',
            field=models.CharField(choices=[('Зг', 'Загальний'), ('Пк', 'Плацкартний'), ('Кп', 'Купейний'), ('Св', 'СВ'), ('Лк', 'Люкс'), ('Св', 'СВ')], max_length=20, verbose_name='Тип вагону'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='service',
            field=models.CharField(choices=[(' ', ' '), ('Пб', 'Постільна білизна'), ('Вд', 'Вода'), ('Гн', 'Гарячі напої')], default=None, max_length=20, verbose_name='Послуги'),
        ),
    ]
