# Generated by Django 3.0.5 on 2020-05-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0009_auto_20200417_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='carriage',
            field=models.IntegerField(default=None, verbose_name='Номер вагону'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number_of_place',
            field=models.IntegerField(default=None, verbose_name='Номер місця'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='place_type',
            field=models.CharField(choices=[('Загальний', 'Загальний'), ('Плацкартний', 'Плацкартний'), ('Купейний', 'Купейний'), ('Св', 'СВ'), ('Люкс', 'Люкс')], max_length=20, verbose_name='Тип вагону'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='service',
            field=models.CharField(choices=[(' ', ' '), ('Постільна білизна', 'Постільна білизна'), ('Вода', 'Вода'), ('Гарячі напої', 'Гарячі напої')], default=None, max_length=20, verbose_name='Послуги'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type_of_ticket',
            field=models.CharField(choices=[('Студентський квиток', 'Студентський квиток'), ('Пільговий', 'Пільговий'), ('Повний', 'Повний')], max_length=20, verbose_name='Тип квитка'),
        ),
    ]
